# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios-watch-extension'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  app.deployment_target = '8.2'
  app.provisioning_profile = 'Watch_Development.mobileprovision'
  app.entitlements['com.apple.security.application-groups'] = ['group.com.company.MagicQWatch']
  
  app.watch_app_config.provisioning_profile = 'Watch_App_Development.mobileprovision'
end

require 'ib/tasks'

IB::RakeTask.new do |project|
  project.resource_directories = ['watch_app']
end
